# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '9.0'
use_frameworks!

pod 'CryptoSwift'
	
	
pod 'SwiftyDropbox', '~> 3.0.0'
	
pod 'Alamofire', '~> 3.0'

target 'MarvelComics' do

end

target 'MarvelComicsTests' do

end

target 'MarvelComicsUITests' do

end

